### ISSUE TITLE
js грешки

### ISSUE THREAD

**Issue by angelk** [ailyak/wordpress_site#2]
Всяка страница дава грешки:
"NetworkError: 404 Not Found - http://ailyak.org/wp-content/themes/revoke/fonts/Comfortaa-Regular.ttf"

You have included the Google Maps API multiple times on this page. This may cause unexpected errors.
https://maps.googleapis.com/maps-api-v3/api/js/22/5a/main.js
Line 67

"NetworkError: 404 Not Found - http://ailyak.org/wp-content/themes/revoke/fonts/futuris.ttf"

**Comment by angelk** [comment]
![ailyak](https://cloud.githubusercontent.com/assets/1329009/10005104/128c19b0-60be-11e5-9388-00837b694a80.png)

**Comment by mariamaneva** [comment]
Фикснах шрифтовете, но това с google maps api май идва от темата

**Comment by angelk** [comment]
ок, затварям го това. Правя нов ишу само за gmaps. https://github.com/ailyak/wordpress_site/issues/6
